dist: trusty

language: bash

addons:
  apt:
    sources:
      - debian-sid
    packages:
      - expect
      - oathtool
      - shellcheck

before_script:
  - wget https://git.zx2c4.com/password-store/snapshot/password-store-1.7.tar.xz
  - tar -xvf password-store-1.7.tar.xz
  - ln -s password-store-1.7/src/password-store.sh pass
  - export PATH=$PATH:.
  - export TEST_OPTS="-v"

install: true

script:
  - make lint
  - cd test && make all
